Repository S4tchel93/GodotGameTest, pull requests merged in 2024-09, with the labels that each got.

#6 Disabled nuke in function game_over
  main.gd
Labels: bug

#8 Settings menu in game
  hud.gd
  options_menu.gd
  options_menu.tscn
  player.gd
  project.godot
Labels: enhancement

#9 Adds possibility to change aim type mouse/keyboard
  main.gd
  main.tscn
  options_menu.gd
  options_menu.tscn
  player.gd
  project.godot
Labels: enhancement, feature

#12 Fixes bug in which player was able to shoot while in the settings menu
  hud.gd
  main.gd
  main.tscn
  options_menu.tscn
  player.gd
Labels: bug fix

#13 Adds the feature to increment score on mob hit
  main.gd
  nuke.gd
Labels: enhancement, feature

#14 Fixes Score Update race condition
  main.gd
  main.tscn
Labels: bug fix
